### ISSUE TITLE
No route found

### ISSUE THREAD

**Issue by SGTGunner** [Hellslicer/fivem-prometheus#1]
I have set the Prometheus exporter on the FX server. I try to validate it with postman. I am running with defaults.
I am getting `Route /prometheus/metrics not found.` and I also tried `Route /metrics not found.` too.

I am running this on a windows server too.

I have no errors. Am I missing something?

Thanks in Advance.

**Comment by SGTGunner** [comment]
Resolved on FiveM forums.

**Comment by tk-aria** [comment]
also faced the same problem. so share the forum link with anyone who encounters a similar issue.

- https://forum.cfx.re/t/release-v8-prometheus/164132/15?u=cityofstreamer
